### ISSUE TITLE
ElasticSearch breaking changes

### ISSUE THREAD

**Issue by sebbalex** [italia/developers-italia-backend#103]
ES7 bring several updates with a lot of enhancements and new features along with performance. It deprecates some of old feats and params, [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response) a list.

Running crawler with `one` command we get:

```
ERRO[0006] json: cannot unmarshal object into Go struct field SearchHits.total of type int64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x161bce1]

goroutine 1 [running]:
github.com/italia/developers-italia-backend/crawler/jekyll.AmministrazioniYML(0xc000b7c450, 0x27, 0xc000ba0000, 0x0, 0x0)
	/Users/sebbalex/workspace/developers-italia-backend/crawler/jekyll/amministrazioni.go:67 +0x741
github.com/italia/developers-italia-backend/crawler/jekyll.GenerateJekyllYML(0xc000ba0000, 0x7ffeefbff790, 0x32)
	/Users/sebbalex/workspace/developers-italia-backend/crawler/jekyll/main.go:22 +0x12e
```

this is due to one of breaking changes of major release.
We should to test accurately against this version and find out whatever there are other problems.

**Comment by bfabio** [comment]
Fixed by #240.
