### ISSUE TITLE
Knowage entry in Developers Italia software catalogue is not updated

### ISSUE THREAD

**Issue by davide-zerbetto** [italia/developers-italia-backend#135]
We modified the publiccode.yml on Knowage github repository, but the entry on Developers Italia software catalogue is not updated, even if validation on public editor was always being successful.

In particular, those changes were not applied (i.e. last 3 commits):
https://github.com/KnowageLabs/Knowage-Server/commit/90fe6d0eb1557257977049a3bfa556802571e1fc#diff-d808908edaf9b9a0101c6225f9d55907
https://github.com/KnowageLabs/Knowage-Server/commit/da72d0ecc80b23e6e7b488f960c405dc123ae071#diff-d808908edaf9b9a0101c6225f9d55907
https://github.com/KnowageLabs/Knowage-Server/commit/61e02f42140d797cc44bf7df8301dba624920608#diff-d808908edaf9b9a0101c6225f9d55907

The only thing that we noticed is that a Knowage screenshot is displayed on search result page when searching for "Knowage", that is fine.

Was Knowage being added into a kind of "bad-publiccode" list?

**Comment by sebbalex** [comment]
Hello @davide-zerbetto actually we are switching infrastructure and this is affecting also data generated from crawler and used then to populate and update Developers Italia's catalog. Here you can track this specific operation: https://github.com/italia/developers.italia.it/pull/529
Sorry for delay.

**Comment by sebbalex** [comment]
Hello @davide-zerbetto here again, migration is now complete and Knowage is correctly listed in catalog:
https://developers.italia.it/it/software/knowagelabs-knowage-server-94e418

Thank you.

**Comment by davide-zerbetto** [comment]
Hello @sebbalex , thank you very much for your prompt reply. Knowage page is "almost" complete, i.e. the first commit (the biggest one) was properly applied, but the other 2 were not. Those 2 commits are quite small indeed, I'm just checking if everything is working fine... Do we simply need to wait a bit for those changes to be applied?

**Comment by sebbalex** [comment]
@davide-zerbetto I just had a look and I see patches correctly applied, could you please check now? Thanks

**Comment by davide-zerbetto** [comment]
@sebbalex I confirm, everything is updated now, thanks
