### ISSUE TITLE
Remove entry from catalog

### ISSUE THREAD

**Issue by libremente** [italia/developers-italia-backend#139]
Sometimes it is necessary to remove an entry from the catalog, see [this policy](https://docs.italia.it/italia/developers-italia/policy-inserimento-catalogo-docs/it/stabile/approvazione-del-software-a-catalogo.html) for more info. 
To accomplish such a goal in the current architecture it is necessary to undergo different paths:
1. [x] remove an entry from the whitelist - accomplished via blacklist mentioned in #78 
2. [x] remove an entry from elasticsearch
3. [x] remove an entry from the `_site` directory - accomplished automatically since everynight the crawler runs from scratch so this is solved via 2. 

It would be nice to have an option to be passed to the crawler via command line to automagically perform the operation described in 2. 
@sebbalex

**Comment by sebbalex** [comment]
We should also consider `administrations`:
Whenever the entry that is going to be removed is the only one who belongs to an administration we should remove it as well. This will avoid to have administrations with no software listed.
@libremente thoughts?

**Comment by sebbalex** [comment]
> We should also consider `administrations`:
> Whenever the entry that is going to be removed is the only one who belongs to an administration we should remove it as well. This will avoid to have administrations with no software listed.
> @libremente thoughts?

never mind administrations data calculation (as specified in PR) is totally stateless and every time are built from scratch.

**Comment by sebbalex** [comment]
> It would be nice to have an option to be passed to the crawler via command line to automagically perform the operation described in 2.

As of https://github.com/italia/developers-italia-backend/pull/140 we got now:

 `bin/crawler delete [URL] delete` software from Elasticsearch using its code hosting URL specified in publiccode.url
