### ISSUE TITLE
Bitbucket raw URL is outside of repository

### ISSUE THREAD

**Issue by libremente** [italia/developers-italia-backend#143]
When dealing with a raw URL from bitbucket the pcvalidate throws a validation ko.
See this repo as an example
```
description/it/screenshots: Absolute URL (https://bitbucket.org/_darti/ssd-arti/raw/ee661d623ebc73edfdc459e280f9fdd0e4c8a5f4/docs/img/assettoIstituzioniScolastiche.jpg) is outside the repository (https://bitbucket.org/_darti/ssd-arti/raw/master/)
```
This does not happen with Github repos.

**Comment by libremente** [comment]
I guess this should be closed by: https://bitbucket.org/_darti/ssd-arti/pull-requests/1/fix-publiccodeyml/diff
It's a weird way of creating the URLs by bb.

**Comment by sebbalex** [comment]
I think this behaviour is just tolerated by Github as shown [here](https://github.com/italia/publiccode-parser-go/blob/master/check_generics.go#L89) we should have the same treatment for all code-hosting platform.

**Comment by bfabio** [comment]
This works with the latest parser version:

❯ pcvalidate/pcvalidate https://bitbucket.org/_darti/ssd-arti/raw/523b9aa0f4cc9e423d1617ceeaf0f6007efea55f/publiccode.yml
publiccode.yml:6:1: warning: publiccodeYmlVersion: v0.2 is not the latest version, use '0.3'. Parsing this file as v0.3.
publiccode.yml:42:5: warning: description.it.genericName: This key is DEPRECATED and will be removed in the future

Closing as fixed.
