### ISSUE TITLE
Failing GETs produce empty repo URL in final catalog page

### ISSUE THREAD

**Issue by libremente** [italia/developers-italia-backend#145]
When there's an error in the pcvalidate's GETs this results in an empty `href` in the frontend. 
Question: is there a way to handle such a situation (is this an exception? probably not...) in a more graceful way?
I believe this opens up a broader question.
The point is that we have to decide how to handle the internal processes fails.
Possibilities:
* every fail means a complete fail. The final page will not be rendered. **The info inserted in ES and in the softwares.yml up until this point have to be rolled back leaving the instance clean**.
* a fail does not mean a complete fail. The final page will be rendered anyway, most probably with some elements missing. We have an inconsistent state. 

I'd try to avoid as much as possible the inconsistency here.
The problem is of course not in the new insertions but with the updates in the publiccode.yml files, since info are already present in ES and we don't want to **override** them if something fails during the process. Ideas @sebbalex? Thanks

**Comment by sebbalex** [comment]
This should be fixed by https://github.com/italia/publiccode-parser-go/pull/25
Now every call is made using auth token, if present, and it will managed by `httpclient` lib which supports rate-limit.
