### ISSUE TITLE
Related softwares don't have codice-IPA attribute

### ISSUE THREAD

**Issue by sebbalex** [italia/developers-italia-backend#150]
As of now related softwares don't have `codice-IPA` attribute which is used to get what type of software is, if it is from reuse channel or third-party.
This is needed for https://github.com/italia/developers.italia.it/pull/561#discussion_r426303850

**Comment by libremente** [comment]
@sebbalex any update on this?

**Comment by sebbalex** [comment]
I moved this in upcoming sprint.
