### ISSUE TITLE
Consider to split this repository removing legacy code

### ISSUE THREAD

**Issue by sebbalex** [italia/developers-italia-backend#155]
After a heavy refactor and some technologies changes decision we should consider to split this repository removing the legacy part which is now obsolete. I see two way in front of us:
- create a dedicated branch
- create a new repository and put it in archive mode

Thoughts are welcome
cc @libremente @LucaPrete

**Comment by LucaPrete** [comment]
I would opt for a new repo as a cleaner solution.

Il giorno mar 7 lug 2020 alle 20:09 Alessandro Sebastiani <
notifications@github.com> ha scritto:

**Comment by libremente** [comment]
Dedicated repo for me.
