### ISSUE TITLE
Gitlab supports subgroups but crawler cannot get their projects

### ISSUE THREAD

**Issue by sebbalex** [italia/developers-italia-backend#156]
Gitlab has support for subgroups and has a specified API, detailed [here](https://docs.gitlab.com/ee/api/groups.html#list-a-groups-subgroups). As of now crawler doesn't support subgroups and when a project is inside of them it won't be crawled.
Actually the only workaround is running crawler in one mode giving project (repository) url as argument.
Question: do we really need to support this feature?
cc @libremente

**Comment by libremente** [comment]
I believe that right now we can put it on hold, since we can "solve" the issue manually by asking the org to change its structure.

**Comment by bfabio** [comment]
We need this one as we onboarded an org with in this exact situation, having to manage different PAs with one GitLab instance

cc @mfortini
