### ISSUE TITLE
developers.italia.it seems to be parsing/presenting languages incorrectly for Greek

### ISSUE THREAD

**Issue by evilaliv3** [italia/developers-italia-backend#162]
Hello i don't know if this is the right place where to notify this but i noticed that the "Greek" language is not parsed/presented correctly on: https://developers.italia.it/it/software/globaleaks-globaleaks-f22648.html

The publiccode.yml of Globaleaks is published here: https://github.com/globaleaks/GlobaLeaks/blob/main/publiccode.yml

![Screenshot_2020-07-14 GlobaLeaks - Developers Italia](https://user-images.githubusercontent.com/217034/87455920-7bf55300-c606-11ea-977f-57a70571e1d6.png)

Thank you for your work!

**Comment by evilaliv3** [comment]
Sure! Thank you so much for this!

**Comment by libremente** [comment]
Hi @evilaliv3, we've inserted this issue in the current sprint so we should be able to triage it soon. Thanks! cc @sebbalex

**Comment by sebbalex** [comment]
Hi @evilaliv3 I'm not sure I get your question. I see Greek correctly listed in your [software page](https://developers.italia.it/it/software/globaleaks-globaleaks-f22648.html). Even in your screen it is correctly present.

[Here](https://github.com/italia/developers.italia.it/blob/master/_data/languages.yml#L109) our mapping model.

Please check this also: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

![Screenshot 2020-07-23 at 15 45 01](https://user-images.githubusercontent.com/11008116/88293627-8b0d8c80-ccfb-11ea-86cb-8ddc49f9fc34.png)

**Comment by evilaliv3** [comment]
Thank you!

Yes it shows up but a bit verbose and confusing as: Greek, Modern (1453-)

**Comment by sebbalex** [comment]
> Thank you! Yes it shows up but a bit verbose and confusing as: Greek, Modern (1453-)

Yes, this is because it refers to actual dialect that is currently in use. I'm closing this.
Thanks.
