### ISSUE TITLE
Use mermaidjs for the diagram in crawler.md

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-backend#194]
I really believe we should use https://mermaid-js.github.io/mermaid/ for this kind of diagrams. 

_Originally posted by @libremente in https://github.com/italia/developers-italia-backend/pull/181#issuecomment-700673049_

**Comment by MattMattV** [comment]
I tried to convert the diagram in #205, I took the liberty to correct the block under "Flush" I thought it was a copy-paste typo.
