### ISSUE TITLE
Path to the list of third-party repositories

### ISSUE THREAD

**Issue by nemobis** [italia/developers-italia-backend#301]
https://developers.italia.it/it/riuso/pubblicazione#software-open-source-di-terze-parti links the old path https://github.com/italia/developers-italia-backend/blob/master/crawler/whitelist/thirdparty.yml which no longer exists since https://github.com/italia/developers-italia-backend/commit/1113650a8dc429cb072d0d7eb1b058821617c564

The new path `publishers.thirparty.yml` also has a typo `thirparty` instead of `thirdparty`.

**Comment by bfabio** [comment]
Thanks, fixed in https://github.com/italia/developers.italia.it/pull/1294 !
