### ISSUE TITLE
Improve logging of bad publiccodes

### ISSUE THREAD

**Issue by alranel** [italia/developers-italia-backend#77]
As of now, the bad_publiccodes.lst file is populated with the raw URLs to the failed publiccodes:

```
https://raw.githubusercontent.com/italia/18app/master/publiccode.yml
```

We should also log the errors and the repository URL (so that it can be easily re-tested with `bin/crawl one <URL>`).

**Comment by sebbalex** [comment]
Logging was implemented in previous version but because of little bug there was not possible to log on file and then debug those situations.

**Comment by sebbalex** [comment]
By default logging library logs everything on stderr we had to modify crontab to log both std out|err on logging directory.
