### ISSUE TITLE
Improve CLI

### ISSUE THREAD

**Issue by alranel** [italia/developers-italia-backend#79]
We need CLI commands for:

- removing contents from the catalog
- dry-run crawling (i.e. without saving to Elasticsearch)

**Comment by bfabio** [comment]
@sebbalex I think we can close this: we already have the `delete` command covering the first point (never used it though). wdyt?

**Comment by sebbalex** [comment]
> @sebbalex I think we can close this: we already have the `delete` command covering the first point (never used it though). wdyt?

Yes, we can close it. `delete` command can be very useful in certain scenario, it is just not so handy, as well other cli commands :). I see two main reasons behind:
- our deployment, of course, as we use it as a k8s job
- the fact that we have two output strategy (Elasticsearch, yaml files) which prevents to use it locally
