### ISSUE TITLE
Include Jaffree in the catalogue

### ISSUE THREAD

**Issue by kokorin** [italia/developers-italia-backend#94]
The publiccode.yml is available here: https://github.com/kokorin/Jaffree/blob/master/publiccode.yml

**Comment by libremente** [comment]
Please see https://github.com/kokorin/Jaffree/pull/57 @kokorin

**Comment by kokorin** [comment]
@libremente done

**Comment by libremente** [comment]
Could you please add a PR for this? Thanks @kokorin

**Comment by kokorin** [comment]
@libremente I wish I could help, but I don't know what and where to change in this repository

**Comment by libremente** [comment]
You should create a PR in the whitelist file appending the name and the repo URL. See https://github.com/italia/developers-italia-backend/pull/107 as an example. Thanks @kokorin

**Comment by kokorin** [comment]
Create pull request #108

**Comment by libremente** [comment]
Thanks @kokorin. Closing. 🎉
